### ISSUE TITLE
convert Country database got error

### ISSUE THREAD

**Issue by nethubonline** [sherpya/geolite2legacy#2]
CentOS Linux release 7.6.1810 (Core)
python-2.7.5-76.el7.x86_64
python-pygeoip-0.2.6-5.el7.noarch
python-ipaddr-2.1.11-1.el7.noarch

Command: 
yum -y install python-ipaddr python-pygeoip
wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
wget https://raw.githubusercontent.com/sherpya/geolite2legacy/master/geolite2legacy.py
chmod 700 geolite2legacy.py
./geolite2legacy.py -i GeoLite2-Country-CSV.zip -o GeoIP.dat

Error :
Traceback (most recent call last):
  File "./geolite2legacy.py", line 202, in <module>
    class ASNv6RadixTree(ASNRadixTree):
  File "./geolite2legacy.py", line 204, in ASNv6RadixTree
    edition = pygeoip.const.ASNUM_EDITION_V6
AttributeError: 'module' object has no attribute 'ASNUM_EDITION_V6'

**Comment by nethubonline** [comment]
After upgraded the pygeoip package, problem is gone, thanks.
