### ISSUE TITLE
python 2.7 ASN conversion results in decode error

### ISSUE THREAD

**Issue by seansweda** [sherpya/geolite2legacy#3]
```
$ pip list 2>/dev/null | egrep 'pygeoip|ipaddr'
ipaddr (2.2.0)
pygeoip (0.3.2)

$ python --version
Python 2.7.15

$ geolite2legacy/geolite2legacy.py -i GeoLite2-ASN-CSV.zip -f geolite2legacy/geoname2fips.csv -o GeoIPASNum.dat
Database type ASN - Blocks IPv4
Traceback (most recent call last):
  File "geolite2legacy/geolite2legacy.py", line 430, in <module>
    main()
  File "geolite2legacy/geolite2legacy.py", line 418, in main
    r.load(locs, TextIOWrapper(ziparchive.open(blocks, 'r'), encoding='utf-8'))
  File "geolite2legacy/geolite2legacy.py", line 143, in load
    for nets, data in self.gen_nets(locations, outfile):
  File "geolite2legacy/geolite2legacy.py", line 211, in gen_nets
    yield nets, (asn.encode('utf-8'),)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

works OK with python 3.6

```
$ python3 geolite2legacy/geolite2legacy.py -i GeoLite2-ASN-CSV.zip -f geolite2legacy/geoname2fips.csv -o GeoIPASNum.dat
Database type ASN - Blocks IPv4
wrote 517773-node trie with 417209 networks (62788 distinct labels) in 18 seconds

```

**Comment by sherpya** [comment]
nevermind, found it

**Comment by sherpya** [comment]
looks like data is encoded using latin, I'm just curious about org with non latin chars

**Comment by sherpya** [comment]
I've fixed the code, but now the output defauls to utf-8, if your software is unable to handle utf-8, try a different encoding using -e

**Comment by seansweda** [comment]
FWIW, I'm seeing the same behavior using 6cf8b15

python3 (3.6.5) works, python2 (2.7.15) bails with the same UnicodeDecodeError

**Comment by seansweda** [comment]
nevermind, I accidentally tested the wrong script

thumbs up
